### Importing libraries
Essential Libraries Let us begin by importing the essential Python Libraries.

- NumPy : Library for Numeric Computations in Python 
- Pandas : Library for Data Acquisition and Preparation 
- Matplotlib : Low-level library for Data Visualization 
- Seaborn : Higher-level library for Data Visualization

In [5]:
# Basic Libraries
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt # we only need pyplot
sb.set() # set the default Seaborn style for graphics

### Exploring '(Kaggle) YouTubeDataset_withChannelElapsed.csv' file

In [6]:
youtubeData = pd.read_csv('(Kaggle) YouTubeDataset_withChannelElapsed.csv')
pd.set_option('display.max_columns', None)
youtubeData.head()

,index,totalviews/channelelapsedtime,channelId,categoryID,channelViewCount,likes/subscriber,views/subscribers,videoCount,subscriberCount,videoId,dislikes/views,channelelapsedtime,comments/subscriber,likes/views,channelCommentCount,videoViewCount,likes/dislikes,comments/views,totvideos/videocount,elapsedtime,videoLikeCount,videoDislikeCount,dislikes/subscriber,totviews/totsubs,views/elapsedtime,videoPublished,VideoCommentCount
0,0,0.165199,UCdzU3DSGzyWzN2118yd9X9g,22,14654,0.555556,95.111111,30,18,--DwgB78t-c,0.000584,88705,0.000000,0.005841,1,1712,-2.0,0.000000,488.466667,50040,10,1,0.055556,814.111111,0.034213,2012-01-19T18:38:28.000Z,0
1,1,1.133820,UC0UnhAG47DRyVZGVcbhAXhQ,10,105909,0.239130,59.326087,51,184,#NAME?,0.000275,93409,0.010870,0.004031,8,10916,-2.0,0.000183,2076.647059,22080,44,3,0.016304,575.592391,0.494384,2015-03-30T04:04:40.000Z,2
2,2,0.668120,UCXjtAvK5P3wXBGh0vbGylzg,27,48265,0.023669,10.289941,72,338,#NAME?,0.000288,72240,0.005917,0.002300,5,3478,-2.0,0.000575,670.347222,71544,8,1,0.002959,142.795858,0.048613,2009-08-07T06:51:10.000Z,2
3,3,25.653505,UCeKHMeUlcLNPLCLUfZUQI2w,26,2116722,0.007301,0.884178,172,22051,#NAME?,0.000308,82512,0.000453,0.008258,74,19497,-2.0,0.000513,12306.523260,54096,161,6,0.000272,95.992109,0.360415,2011-08-04T01:07:38.000Z,10
4,4,52.773778,UCNWPDyaWf2eAHnofFLSnEMg,20,1649075,0.004545,10.004545,2777,220,--7h1S4neDM,0.000000,31248,0.000000,0.000454,0,2201,-2.0,0.000000,593.833273,30120,1,0,0.000000,7495.795455,0.073074,2014-04-29T15:44:44.000Z,0

### Exploring '(GitHub) categoryID.csv' file and displaying it

In [7]:
categoryID = pd.read_csv('(GitHub) categoryID.csv')
categoryID = categoryID.drop(columns=['channelID'])
categoryID.head()

   categoryID             Title
0           1  Film & Animation
1           2  Autos & Vehicles
2          10             Music
3          15    Pets & Animals
4          17            Sports

## 1. Merging two datasets based on category ID to fill in the missing variable of 'Title'

In [8]:
mergedData = pd.merge(youtubeData, categoryID)
pd.set_option('display.max_columns', None)
mergedData.head()

,index,totalviews/channelelapsedtime,channelId,categoryID,channelViewCount,likes/subscriber,views/subscribers,videoCount,subscriberCount,videoId,dislikes/views,channelelapsedtime,comments/subscriber,likes/views,channelCommentCount,videoViewCount,likes/dislikes,comments/views,totvideos/videocount,elapsedtime,videoLikeCount,videoDislikeCount,dislikes/subscriber,totviews/totsubs,views/elapsedtime,videoPublished,VideoCommentCount,Title
0,0,0.165199,UCdzU3DSGzyWzN2118yd9X9g,22,14654,0.555556,95.111111,30,18,--DwgB78t-c,0.000584,88705,0.000000,0.005841,1,1712,-2.0,0.000000,488.466667,50040,10,1,0.055556,814.111111,0.034213,2012-01-19T18:38:28.000Z,0,People & Blogs
1,18,0.537747,UCIqxsYQqmf-1rP7w18cDAkg,22,23734,0.076923,316.461539,8,13,#NAME?,0.000486,44136,0.076923,0.000243,0,4114,-2.0,0.000243,2966.750000,43896,1,2,0.153846,1825.692308,0.093722,2012-10-01T19:38:57.000Z,1,People & Blogs
2,21,0.277610,UCpJ-kuYqO3-FmecU4hViajw,22,26904,0.072727,55.545455,4,55,#NAME?,0.000655,96913,0.018182,0.001309,0,3055,-2.0,0.000327,6726.000000,63168,4,2,0.036364,489.163636,0.048363,2010-07-22T08:40:52.000Z,1,People & Blogs
3,48,0.201935,UCyNzS_6-B9hnZWemuBpQgEg,22,14423,0.200000,195.600000,31,15,--mhuht-0tE,0.000000,71424,0.066667,0.001022,0,2934,-2.0,0.000341,465.258064,71400,3,0,0.000000,961.533333,0.041092,2009-08-13T14:33:38.000Z,1,People & Blogs
4,58,0.267540,UCSZUXGdzweAuksqVrrbj2Iw,22,13484,0.090909,195.454545,7,11,#NAME?,0.000465,50400,0.000000,0.000465,0,2150,-2.0,0.000000,1926.285714,50376,1,1,0.090909,1225.818182,0.042679,2012-01-06T10:07:49.000Z,0,People & Blogs

In [9]:
mergedData.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 571960 entries, 0 to 571959
Data columns (total 28 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   index                          571960 non-null  int64
 1   totalviews/channelelapsedtime  571960 non-null  float64
 2   channelId                      571960 non-null  object
 3   categoryID                     571960 non-null  int64
 4   channelViewCount               571960 non-null  int64
 5   likes/subscriber               571960 non-null  float64
 6   views/subscribers              571960 non-null  float64
 7   videoCount                     571960 non-null  int64
 8   subscriberCount                571960 non-null  int64
 9   videoId                        571960 non-null  object
 10  dislikes/views                 571960 non-null  float64
 11  channelelapsedtime             571960 non-null  int64
 12  comments/subscriber            571960 non-null  float64
 13  likes/views                    571960 non-null  float64
 14  channelCommentCount            571960 non-null  int64
 15  videoViewCount                 571960 non-null  int64
 16  likes/dislikes                 571960 non-null  float64
 17  comments/views                 571960 non-null  float64
 18  totvideos/videocount           571960 non-null  float64
 19  elapsedtime                    571960 non-null  int64
 20  videoLikeCount                 571960 non-null  int64
 21  videoDislikeCount              571960 non-null  int64
 22  dislikes/subscriber            571960 non-null  float64
 23  totviews/totsubs               571960 non-null  float64
 24  views/elapsedtime              571960 non-null  float64
 25  videoPublished                 571960 non-null  object
 26  VideoCommentCount              571960 non-null  int64
 27  Title                          571960 non-null  object
dtypes: float64(12), int64(12), object(4)
memory usage: 126.5+ MB

In [10]:
UniqueCount = mergedData["Title"].value_counts().to_dict()
print(UniqueCount)

{'Music': 111095, 'Entertainment': 74075, 'Gaming': 72547, 'People & Blogs': 70030, 'Sports': 60154, 'Autos & Vehicles': 35585, 'Howto & Style': 33131, 'Film & Animation': 26072, 'Science & Technology': 21397, 'Education': 16925, 'Travel & Events': 15928, 'Comedy': 12941, 'Pets & Animals': 10188, 'News & Politics': 10008, 'Shows': 1663, 'Trailers': 217, 'Movies': 4}

In [11]:
mergedData['GenreCount'] = mergedData["Title"].map(UniqueCount)

In [12]:
mergedData[['Title', 'GenreCount']]

                 Title  GenreCount
0       People & Blogs       70030
1       People & Blogs       70030
2       People & Blogs       70030
3       People & Blogs       70030
4       People & Blogs       70030
...                ...         ...
571955        Trailers         217
571956          Movies           4
571957          Movies           4
571958          Movies           4
571959          Movies           4

[571960 rows x 2 columns]

### 2. Finding relationship between PublishedDate and videoViewCount

In [16]:
import datetime as DT

In [17]:
CurrentDate = DT.datetime.strptime("2023-03-30", "%Y-%M-%d")

In [18]:
str_d1=mergedData['videoPublished'][0][:10]

#convert date in string format to date object
d1 = DT.datetime.strptime(str_d1, "%Y-%m-%d")

In [19]:
DatePast = CurrentDate - d1

In [20]:
print(DatePast.days)

4029

In [25]:
CurrentDate = DT.datetime.strptime("2023-03-30", "%Y-%M-%d")
mergedData['convertedVideoPublished'] =""
mergedData['dateDifference']=""

### 2.1 Creating a new column named "dateDifference"

In [ ]:
for i in range(571960):
    mergedData['convertedVideoPublished'][i]= mergedData['videoPublished'][i][:10]
    #mergeddata['convertedVideoPublished'][i] = DT.datetime.strptime(mergeddata['convertedVideoPublished'][i],"%Y-%m-%d" )
    dNew = DT.datetime.strptime(mergedData['convertedVideoPublished'][i],"%Y-%m-%d" )
    mergedData['dateDifference'][i]= (CurrentDate - dNew).days

C:\Users\Wise 240gb\AppData\Local\Temp\ipykernel_1992\488416338.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mergedData['convertedVideoPublished'][i]= mergedData['videoPublished'][i][:10]
C:\Users\Wise 240gb\AppData\Local\Temp\ipykernel_1992\488416338.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mergedData['dateDifference'][i]= (CurrentDate - dNew).days

In [ ]:
mergedData

## 3. After data cleaning and preprocessing, final dataset to work on is Updated.csv

In [ ]:
mergedData.to_csv('Updated.csv')